DROP TABLE user_accounts;
DROP TABLE tickets;
DROP TABLE events;
DROP TABLE users;

CREATE TABLE events (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"date" timestamp(6) NULL,
	ticket_price numeric(38, 2) NULL,
	title varchar(255) NULL,
	CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE tickets (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	category int2 NULL,
	place int4 NOT NULL,
	event_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT tickets_category_check CHECK (((category >= 0) AND (category <= 2))),
	CONSTRAINT tickets_pkey PRIMARY KEY (id),
	CONSTRAINT tickets_event_id_fk FOREIGN KEY (event_id) REFERENCES events(id),
	CONSTRAINT tickets_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_accounts (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	balance numeric(38, 2) NULL,
	user_id int8 NULL,
	CONSTRAINT user_accounts_user_id_unique UNIQUE (user_id),
	CONSTRAINT user_accounts_pkey PRIMARY KEY (id),
	CONSTRAINT user_accounts_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id)
);